[colors]
  [colors.primary]
    background = "#222222"
    foreground = "#D0D0D0"

  [colors.normal]
    black = "#151515"
    red = "#A53C23"
    green = "#7B9246"
    yellow = "#D3A04D"
    blue = "#6C99BB"
    magenta = "#9F4E85"
    cyan = "#7DD6CF"
    white = "#D0D0D0"

  [colors.bright]
    black = "#505050"
    red = "#A53C23"
    green = "#7B9246"
    yellow = "#D3A04D"
    blue = "#547C99"
    magenta = "#9F4E85"
    cyan = "#7DD6CF"
    white = "#F5F5F5"
