[colors]
  [colors.primary]
    background = "#161719"
    foreground = "#C5C8C6"

  [colors.normal]
    black = "#000000"
    red = "#FD5FF1"
    green = "#87C38A"
    yellow = "#FFD7B1"
    blue = "#85BEFD"
    magenta = "#B9B6FC"
    cyan = "#85BEFD"
    white = "#E0E0E0"

  [colors.bright]
    black = "#000000"
    red = "#FD5FF1"
    green = "#94FA36"
    yellow = "#F5FFA8"
    blue = "#96CBFE"
    magenta = "#B9B6FC"
    cyan = "#85BEFD"
    white = "#E0E0E0"
