[colors]
  [colors.primary]
    background = "#FAFAFA"
    foreground = "#575F66"

  [colors.normal]
    black = "#575F66"
    red = "#F51818"
    green = "#86B300"
    yellow = "#F2AE49"
    blue = "#399EE6"
    magenta = "#A37ACC"
    cyan = "#4CBF99"
    white = "#FAFAFA"

  [colors.bright]
    black = "#8A9199"
    red = "#F51818"
    green = "#86B300"
    yellow = "#F2AE49"
    blue = "#399EE6"
    magenta = "#A37ACC"
    cyan = "#4CBF99"
    white = "#FAFAFA"
