[colors]
  [colors.primary]
    background = "#0D1926"
    foreground = "#D9E6F2"

  [colors.normal]
    black = "#000000"
    red = "#B87A7A"
    green = "#7AB87A"
    yellow = "#B8B87A"
    blue = "#7A7AB8"
    magenta = "#B87AB8"
    cyan = "#7AB8B8"
    white = "#D9D9D9"

  [colors.bright]
    black = "#262626"
    red = "#DBBDBD"
    green = "#BDDBBD"
    yellow = "#DBDBBD"
    blue = "#BDBDDB"
    magenta = "#DBBDDB"
    cyan = "#BDDBDB"
    white = "#FFFFFF"
