[colors]
  [colors.primary]
    background = "#09111A"
    foreground = "#D9E6F2"

  [colors.normal]
    black = "#000000"
    red = "#CA274D"
    green = "#4DCA27"
    yellow = "#CAA427"
    blue = "#274DCA"
    magenta = "#A427CA"
    cyan = "#27CAA4"
    white = "#808080"

  [colors.bright]
    black = "#808080"
    red = "#E98DA3"
    green = "#A3E98D"
    yellow = "#E9D48D"
    blue = "#8DA3E9"
    magenta = "#D48DE9"
    cyan = "#8DE9D4"
    white = "#FFFFFF"
