[colors]
  [colors.primary]
    background = "#EFF1F5"
    foreground = "#4C4F69"

  [colors.normal]
    black = "#5C5F77"
    red = "#D20F39"
    green = "#40A02B"
    yellow = "#DF8E1D"
    blue = "#1E66F5"
    magenta = "#EA76CB"
    cyan = "#179299"
    white = "#ACB0BE"

  [colors.bright]
    black = "#6C6F85"
    red = "#D20F39"
    green = "#40A02B"
    yellow = "#DF8E1D"
    blue = "#1E66F5"
    magenta = "#EA76CB"
    cyan = "#179299"
    white = "#BCC0CC"
