[colors]
  [colors.primary]
    background = "#29262F"
    foreground = "#D9E6F2"

  [colors.normal]
    black = "#000000"
    red = "#C37372"
    green = "#72C373"
    yellow = "#C2C372"
    blue = "#7372C3"
    magenta = "#C372C2"
    cyan = "#72C2C3"
    white = "#D9D9D9"

  [colors.bright]
    black = "#323232"
    red = "#DBAAAA"
    green = "#AADBAA"
    yellow = "#DADBAA"
    blue = "#AAAADB"
    magenta = "#DBAADA"
    cyan = "#AADADB"
    white = "#FFFFFF"
