[colors]
  [colors.primary]
    background = "#171D23"
    foreground = "#FFFFFF"

  [colors.normal]
    black = "#41505E"
    red = "#D95468"
    green = "#8BD49C"
    yellow = "#EBBF83"
    blue = "#539AFC"
    magenta = "#B62D65"
    cyan = "#70E1E8"
    white = "#FFFFFF"

  [colors.bright]
    black = "#41505E"
    red = "#D95468"
    green = "#8BD49C"
    yellow = "#EBBF83"
    blue = "#539AFC"
    magenta = "#B62D65"
    cyan = "#70E1E8"
    white = "#FFFFFF"
