[colors]
  [colors.primary]
    background = "#333333"
    foreground = "#FFFFFF"

  [colors.normal]
    black = "#4D4D4D"
    red = "#FF2B2B"
    green = "#98FB98"
    yellow = "#F0E68C"
    blue = "#CD853F"
    magenta = "#FFDEAD"
    cyan = "#FFA0A0"
    white = "#F5DEB3"

  [colors.bright]
    black = "#555555"
    red = "#FF5555"
    green = "#55FF55"
    yellow = "#FFFF55"
    blue = "#87CEFF"
    magenta = "#FF55FF"
    cyan = "#FFD700"
    white = "#FFFFFF"
