[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#FFFFFF"

  [colors.normal]
    black = "#000000"
    red = "#DC322F"
    green = "#56DB3A"
    yellow = "#FF8400"
    blue = "#0084D4"
    magenta = "#B729D9"
    cyan = "#CCCCFF"
    white = "#FFFFFF"

  [colors.bright]
    black = "#D6DBE5"
    red = "#DC322F"
    green = "#56DB3A"
    yellow = "#FF8400"
    blue = "#0084D4"
    magenta = "#B729D9"
    cyan = "#CCCCFF"
    white = "#FFFFFF"
