[colors]
  [colors.primary]
    background = "#292520"
    foreground = "#E5C7A9"

  [colors.normal]
    black = "#121418"
    red = "#C94234"
    green = "#85C54C"
    yellow = "#F5AE2E"
    blue = "#1398B9"
    magenta = "#D0633D"
    cyan = "#509552"
    white = "#E5C6AA"

  [colors.bright]
    black = "#675F54"
    red = "#FF645A"
    green = "#98E036"
    yellow = "#E0D561"
    blue = "#5FDAFF"
    magenta = "#FF9269"
    cyan = "#84F088"
    white = "#F6F7EC"
