[colors]
  [colors.primary]
    background = "#22211D"
    foreground = "#807A74"

  [colors.normal]
    black = "#3C3C30"
    red = "#98290F"
    green = "#479A43"
    yellow = "#7F7111"
    blue = "#497F7D"
    magenta = "#7F4E2F"
    cyan = "#387F58"
    white = "#807974"

  [colors.bright]
    black = "#555445"
    red = "#E0502A"
    green = "#61E070"
    yellow = "#D69927"
    blue = "#79D9D9"
    magenta = "#CD7C54"
    cyan = "#59D599"
    white = "#FFF1E9"
