[colors]
  [colors.primary]
    background = "#4A453E"
    foreground = "#F2F2F2"

  [colors.normal]
    black = "#303030"
    red = "#E1321A"
    green = "#6AB017"
    yellow = "#FFC005"
    blue = "#729FCF"
    magenta = "#EC0048"
    cyan = "#F2F2F2"
    white = "#2AA7E7"

  [colors.bright]
    black = "#5D5D5D"
    red = "#FF361E"
    green = "#7BC91F"
    yellow = "#FFD00A"
    blue = "#0071FF"
    magenta = "#FF1D62"
    cyan = "#4BB8FD"
    white = "#A020F0"
