[colors]
  [colors.primary]
    background = "#141B1E"
    foreground = "#DADADA"

  [colors.normal]
    black = "#232A2D"
    red = "#E57474"
    green = "#8CCF7E"
    yellow = "#E5C76B"
    blue = "#67B0E8"
    magenta = "#C47FD5"
    cyan = "#6CBFBF"
    white = "#B3B9B8"

  [colors.bright]
    black = "#2D3437"
    red = "#EF7E7E"
    green = "#96D988"
    yellow = "#F4D67A"
    blue = "#71BAF2"
    magenta = "#CE89DF"
    cyan = "#67CBE7"
    white = "#BDC3C2"
