[colors]
  [colors.primary]
    background = "#1D1F21"
    foreground = "#B8DBEF"

  [colors.normal]
    black = "#1D1D19"
    red = "#F18339"
    green = "#9FD364"
    yellow = "#F4EF6D"
    blue = "#5096BE"
    magenta = "#695ABC"
    cyan = "#D63865"
    white = "#FFFFFF"

  [colors.bright]
    black = "#1D1D19"
    red = "#D22A24"
    green = "#A7D42C"
    yellow = "#FF8949"
    blue = "#61B9D0"
    magenta = "#695ABC"
    cyan = "#D63865"
    white = "#FFFFFF"
