[colors]
  [colors.primary]
    background = "#f6f8fa"
    foreground = "#1f2328"

  [colors.normal]
    black = "#24292f"
    red = "#cf222e"
    green = "#1a7f37"
    yellow = "#9a6700"
    blue = "#0969da"
    magenta = "#8250df"
    cyan = "#1b7c83"
    white = "#6e7781"

  [colors.bright]
    black = "#57606a"
    red = "#a40e26"
    green = "#2da44e"
    yellow = "#bf8700"
    blue = "#218bff"
    magenta = "#a475f9"
    cyan = "#3192aa"
    white = "#8c959f"
