[colors]
  [colors.primary]
    background = "#292D3E"
    foreground = "#BFC7D5"

  [colors.normal]
    black = "#292D3E"
    red = "#F07178"
    green = "#62DE84"
    yellow = "#FFCB6B"
    blue = "#75A1FF"
    magenta = "#F580FF"
    cyan = "#60BAEC"
    white = "#ABB2BF"

  [colors.bright]
    black = "#959DCB"
    red = "#F07178"
    green = "#C3E88D"
    yellow = "#FF5572"
    blue = "#82AAFF"
    magenta = "#FFCB6B"
    cyan = "#676E95"
    white = "#FFFEFE"
