[colors]
  [colors.primary]
    background = "#0D101B"
    foreground = "#EBEEF9"

  [colors.normal]
    black = "#000009"
    red = "#BB4F6C"
    green = "#72CCAE"
    yellow = "#C65E3D"
    blue = "#58B6CA"
    magenta = "#6488C4"
    cyan = "#8D84C6"
    white = "#858893"

  [colors.bright]
    black = "#1F222D"
    red = "#EE829F"
    green = "#A5FFE1"
    yellow = "#F99170"
    blue = "#8BE9FD"
    magenta = "#97BBF7"
    cyan = "#C0B7F9"
    white = "#FFFFFF"
