[colors]
  [colors.primary]
    background = "#171423"
    foreground = "#9F9FA1"

  [colors.normal]
    black = "#2D283F"
    red = "#ED2261"
    green = "#1FA91B"
    yellow = "#8DDC20"
    blue = "#487DF4"
    magenta = "#8D35C9"
    cyan = "#3BDEED"
    white = "#9E9EA0"

  [colors.bright]
    black = "#59516A"
    red = "#F0729A"
    green = "#53AA5E"
    yellow = "#B2DC87"
    blue = "#A9BCEC"
    magenta = "#AD81C2"
    cyan = "#9DE3EB"
    white = "#A288F7"
