[colors]
  [colors.primary]
    background = "#1C1E26"
    foreground = "#FDF0ED"

  [colors.normal]
    black = "#16161C"
    red = "#E95678"
    green = "#29D398"
    yellow = "#FAB795"
    blue = "#26BBD9"
    magenta = "#EE64AE"
    cyan = "#59E3E3"
    white = "#FADAD1"

  [colors.bright]
    black = "#232530"
    red = "#EC6A88"
    green = "#3FDAA4"
    yellow = "#FBC3A7"
    blue = "#3FC6DE"
    magenta = "#F075B7"
    cyan = "#6BE6E6"
    white = "#FDF0ED"
