[colors]
  [colors.primary]
    background = "#141414"
    foreground = "#94A3A5"

  [colors.normal]
    black = "#282A2E"
    red = "#A54242"
    green = "#8C9440"
    yellow = "#DE935F"
    blue = "#5F819D"
    magenta = "#85678F"
    cyan = "#5E8D87"
    white = "#969896"

  [colors.bright]
    black = "#373B41"
    red = "#CC6666"
    green = "#B5BD68"
    yellow = "#F0C674"
    blue = "#81A2BE"
    magenta = "#B294BB"
    cyan = "#8ABEB7"
    white = "#C5C8C6"
