[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#FDFDFD"

  [colors.normal]
    black = "#000000"
    red = "#FF0000"
    green = "#00FF00"
    yellow = "#FFFF00"
    blue = "#00BFFF"
    magenta = "#FFC0CB"
    cyan = "#40E0D0"
    white = "#BEBEBE"

  [colors.bright]
    black = "#414141"
    red = "#FFA500"
    green = "#98FB98"
    yellow = "#FFFF00"
    blue = "#0000CD"
    magenta = "#A020F0"
    cyan = "#AEEEEE"
    white = "#FFFFFF"
