[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#FDFDFD"

  [colors.normal]
    black = "#222222"
    red = "#F01818"
    green = "#24D830"
    yellow = "#F0D824"
    blue = "#7890F0"
    magenta = "#F078D8"
    cyan = "#54E4E4"
    white = "#A5A5A5"

  [colors.bright]
    black = "#888888"
    red = "#EF8383"
    green = "#7ED684"
    yellow = "#EFE28B"
    blue = "#B3BFEF"
    magenta = "#EFB3E3"
    cyan = "#9CE2E2"
    white = "#FFFFFF"
