[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#AFC2C2"

  [colors.normal]
    black = "#000000"
    red = "#FF3030"
    green = "#559A70"
    yellow = "#CCAC00"
    blue = "#0099CC"
    magenta = "#CC69C8"
    cyan = "#7AC4CC"
    white = "#BCCCCC"

  [colors.bright]
    black = "#000000"
    red = "#FF3030"
    green = "#559A70"
    yellow = "#CCAC00"
    blue = "#0099CC"
    magenta = "#CC69C8"
    cyan = "#7AC4CC"
    white = "#BCCCCC"
