[colors]
  [colors.primary]
    background = "#ffffff"
    foreground = "#000000"

  [colors.normal]
    black = "#ffffff"
    red = "#a60000"
    green = "#006800"
    yellow = "#6f5500"
    blue = "#0031a9"
    magenta = "#721045"
    cyan = "#005e8b"
    white = "#000000"

  [colors.bright]
    black = "#f2f2f2"
    red = "#d00000"
    green = "#008900"
    yellow = "#808000"
    blue = "#0000ff"
    magenta = "#dd22dd"
    cyan = "#008899"
    white = "#595959"
