[colors]
  [colors.primary]
    background = "#0d0e1c"
    foreground = "#ffffff"

  [colors.normal]
    black = "#0d0e1c"
    red = "#ff5f59"
    green = "#44bc44"
    yellow = "#d0bc00"
    blue = "#2fafff"
    magenta = "#feacd0"
    cyan = "#00d3d0"
    white = "#ffffff"

  [colors.bright]
    black = "#1d2235"
    red = "#ff5f5f"
    green = "#44df44"
    yellow = "#efef00"
    blue = "#338fff"
    magenta = "#ff66ff"
    cyan = "#00eff0"
    white = "#989898"
