[colors]
  [colors.primary]
    background = "#120B0D"
    foreground = "#F7D66A"

  [colors.normal]
    black = "#351B0E"
    red = "#9B291C"
    green = "#636232"
    yellow = "#C36E28"
    blue = "#515C5D"
    magenta = "#9B1D29"
    cyan = "#588056"
    white = "#F7D75C"

  [colors.bright]
    black = "#874228"
    red = "#FF4331"
    green = "#B4B264"
    yellow = "#FF9566"
    blue = "#9EB2B4"
    magenta = "#FF5B6A"
    cyan = "#8ACD8F"
    white = "#FFE598"
