[colors]
  [colors.primary]
    background = "#2B1900"
    foreground = "#FF9400"

  [colors.normal]
    black = "#402500"
    red = "#FF9400"
    green = "#FF9400"
    yellow = "#FF9400"
    blue = "#FF9400"
    magenta = "#FF9400"
    cyan = "#FF9400"
    white = "#FF9400"

  [colors.bright]
    black = "#FF9400"
    red = "#FF9400"
    green = "#FF9400"
    yellow = "#FF9400"
    blue = "#FF9400"
    magenta = "#FF9400"
    cyan = "#FF9400"
    white = "#FF9400"
