[colors]
  [colors.primary]
    background = "#262626"
    foreground = "#FAFAFA"

  [colors.normal]
    black = "#3B3B3B"
    red = "#FAFAFA"
    green = "#FAFAFA"
    yellow = "#FAFAFA"
    blue = "#FAFAFA"
    magenta = "#FAFAFA"
    cyan = "#FAFAFA"
    white = "#FAFAFA"

  [colors.bright]
    black = "#FAFAFA"
    red = "#FAFAFA"
    green = "#FAFAFA"
    yellow = "#FAFAFA"
    blue = "#FAFAFA"
    magenta = "#FAFAFA"
    cyan = "#FAFAFA"
    white = "#FAFAFA"
