[colors]
  [colors.primary]
    background = "#363537"
    foreground = "#FDF9F3"

  [colors.normal]
    black = "#363537"
    red = "#FF6188"
    green = "#A9DC76"
    yellow = "#FFD866"
    blue = "#FC9867"
    magenta = "#AB9DF2"
    cyan = "#78DCE8"
    white = "#FDF9F3"

  [colors.bright]
    black = "#908E8F"
    red = "#FF6188"
    green = "#A9DC76"
    yellow = "#FFD866"
    blue = "#FC9867"
    magenta = "#AB9DF2"
    cyan = "#78DCE8"
    white = "#FDF9F3"
