[colors]
  [colors.primary]
    background = "#EBEAF2"
    foreground = "#004F7C"

  [colors.normal]
    black = "#003B4E"
    red = "#E64569"
    green = "#069F5F"
    yellow = "#DAB752"
    blue = "#439ECF"
    magenta = "#D961DC"
    cyan = "#00B1BE"
    white = "#B3B3B3"

  [colors.bright]
    black = "#3E89A1"
    red = "#E4859A"
    green = "#A2CCA1"
    yellow = "#E1E387"
    blue = "#6FBBE2"
    magenta = "#E586E7"
    cyan = "#96DCDA"
    white = "#DEDEDE"
