[colors]
  [colors.primary]
    background = "#F8F8F8"
    foreground = "#2A2B32"

  [colors.normal]
    black = "#000000"
    red = "#DA3E39"
    green = "#41933E"
    yellow = "#855504"
    blue = "#315EEE"
    magenta = "#930092"
    cyan = "#0E6FAD"
    white = "#8E8F96"

  [colors.bright]
    black = "#2A2B32"
    red = "#DA3E39"
    green = "#41933E"
    yellow = "#855504"
    blue = "#315EEE"
    magenta = "#930092"
    cyan = "#0E6FAD"
    white = "#FFFEFE"
