[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#DCDFE4"

  [colors.normal]
    black = "#282C34"
    red = "#E06C75"
    green = "#98C379"
    yellow = "#E5C07B"
    blue = "#61AFEF"
    magenta = "#C678DD"
    cyan = "#56B6C2"
    white = "#DCDFE4"

  [colors.bright]
    black = "#282C34"
    red = "#E06C75"
    green = "#98C379"
    yellow = "#E5C07B"
    blue = "#61AFEF"
    magenta = "#C678DD"
    cyan = "#56B6C2"
    white = "#DCDFE4"
