[colors]
  [colors.primary]
    background = "#EEEEEE"
    foreground = "#444444"

  [colors.normal]
    black = "#EEEEEE"
    red = "#AF0000"
    green = "#008700"
    yellow = "#5F8700"
    blue = "#0087AF"
    magenta = "#878787"
    cyan = "#005F87"
    white = "#444444"

  [colors.bright]
    black = "#BCBCBC"
    red = "#D70000"
    green = "#D70087"
    yellow = "#8700AF"
    blue = "#D75F00"
    magenta = "#D75F00"
    cyan = "#005FAF"
    white = "#005F87"
