[colors]
  [colors.primary]
    background = "#241F33"
    foreground = "#D1CAE8"

  [colors.normal]
    black = "#2F2942"
    red = "#FF857F"
    green = "#48B685"
    yellow = "#E6C000"
    blue = "#AE81FF"
    magenta = "#EF6155"
    cyan = "#C2FFDF"
    white = "#F8F8F2"

  [colors.bright]
    black = "#75507B"
    red = "#F1568E"
    green = "#5ADBA2"
    yellow = "#D5A425"
    blue = "#C5A3FF"
    magenta = "#EF6155"
    cyan = "#C2FFFF"
    white = "#F8F8F0"
