[colors]
  [colors.primary]
    background = "#1C1C1C"
    foreground = "#D0D0D0"

  [colors.normal]
    black = "#2F2E2D"
    red = "#A36666"
    green = "#90A57D"
    yellow = "#D7AF87"
    blue = "#7FA5BD"
    magenta = "#C79EC4"
    cyan = "#8ADBB4"
    white = "#D0D0D0"

  [colors.bright]
    black = "#4A4845"
    red = "#D78787"
    green = "#AFBEA2"
    yellow = "#E4C9AF"
    blue = "#A1BDCE"
    magenta = "#D7BEDA"
    cyan = "#B1E7DD"
    white = "#EFEFEF"
