[colors]
  [colors.primary]
    background = "#052454"
    foreground = "#F6F6F7"

  [colors.normal]
    black = "#000000"
    red = "#7E0008"
    green = "#098003"
    yellow = "#C4A000"
    blue = "#010083"
    magenta = "#D33682"
    cyan = "#0E807F"
    white = "#7F7C7F"

  [colors.bright]
    black = "#808080"
    red = "#EF2929"
    green = "#1CFE3C"
    yellow = "#FEFE45"
    blue = "#268AD2"
    magenta = "#FE13FA"
    cyan = "#29FFFE"
    white = "#C2C1C3"
