[colors]
  [colors.primary]
    background = "#232136"
    foreground = "#E0DEF4"

  [colors.normal]
    black = "#393552"
    red = "#EB6F92"
    green = "#9CCFD8"
    yellow = "#F6C177"
    blue = "#3E8FB0"
    magenta = "#C4A7E7"
    cyan = "#EA9A97"
    white = "#E0DEF4"

  [colors.bright]
    black = "#6E6A86"
    red = "#EB6F92"
    green = "#9CCFD8"
    yellow = "#F6C177"
    blue = "#3E8FB0"
    magenta = "#C4A7E7"
    cyan = "#EA9A97"
    white = "#E0DEF4"
