[colors]
  [colors.primary]
    background = "#758480"
    foreground = "#23476A"

  [colors.normal]
    black = "#000000"
    red = "#DD0007"
    green = "#07DD00"
    yellow = "#DDD600"
    blue = "#0007DD"
    magenta = "#D600DD"
    cyan = "#00DDD6"
    white = "#F2F2F2"

  [colors.bright]
    black = "#7D7D7D"
    red = "#FF7478"
    green = "#78FF74"
    yellow = "#FFFA74"
    blue = "#7478FF"
    magenta = "#FA74FF"
    cyan = "#74FFFA"
    white = "#FFFFFF"
