[colors]
  [colors.primary]
    background = "#09141B"
    foreground = "#DEB88D"

  [colors.normal]
    black = "#17384C"
    red = "#D15123"
    green = "#027C9B"
    yellow = "#FCA02F"
    blue = "#1E4950"
    magenta = "#68D4F1"
    cyan = "#50A3B5"
    white = "#DEB88D"

  [colors.bright]
    black = "#434B53"
    red = "#D48678"
    green = "#628D98"
    yellow = "#FDD39F"
    blue = "#1BBCDD"
    magenta = "#BBE3EE"
    cyan = "#87ACB4"
    white = "#FEE4CE"
