[colors]
  [colors.primary]
    background = "#3D3F41"
    foreground = "#D2D8D9"

  [colors.normal]
    black = "#25292A"
    red = "#F24840"
    green = "#629655"
    yellow = "#B68800"
    blue = "#2075C7"
    magenta = "#797FD4"
    cyan = "#15968D"
    white = "#D2D8D9"

  [colors.bright]
    black = "#25292A"
    red = "#F24840"
    green = "#629655"
    yellow = "#B68800"
    blue = "#2075C7"
    magenta = "#797FD4"
    cyan = "#15968D"
    white = "#D2D8D9"
