[colors]
  [colors.primary]
    background = "#2C2E34"
    foreground = "#E2E2E3"

  [colors.normal]
    black = "#2C2E34"
    red = "#FC5D7C"
    green = "#9ED072"
    yellow = "#E7C664"
    blue = "#F39660"
    magenta = "#B39DF3"
    cyan = "#76CCE0"
    white = "#E2E2E3"

  [colors.bright]
    black = "#7F8490"
    red = "#FC5D7C"
    green = "#9ED072"
    yellow = "#E7C664"
    blue = "#F39660"
    magenta = "#B39DF3"
    cyan = "#76CCE0"
    white = "#E2E2E3"
