[colors]
  [colors.primary]
    background = "#20242D"
    foreground = "#B3B8C3"

  [colors.normal]
    black = "#000000"
    red = "#B04B57"
    green = "#87B379"
    yellow = "#E5C179"
    blue = "#7D8FA4"
    magenta = "#A47996"
    cyan = "#85A7A5"
    white = "#B3B8C3"

  [colors.bright]
    black = "#000000"
    red = "#B04B57"
    green = "#87B379"
    yellow = "#E5C179"
    blue = "#7D8FA4"
    magenta = "#A47996"
    cyan = "#85A7A5"
    white = "#FFFFFF"
