[colors]
  [colors.primary]
    background = "#0A1E24"
    foreground = "#ECF0C1"

  [colors.normal]
    black = "#6E5346"
    red = "#E35B00"
    green = "#5CAB96"
    yellow = "#E3CD7B"
    blue = "#0F548B"
    magenta = "#E35B00"
    cyan = "#06AFC7"
    white = "#F0F1CE"

  [colors.bright]
    black = "#684C31"
    red = "#FF8A3A"
    green = "#AECAB8"
    yellow = "#FFC878"
    blue = "#67A0CE"
    magenta = "#FF8A3A"
    cyan = "#83A7B4"
    white = "#FEFFF1"
