[colors]
  [colors.primary]
    background = "#0A1E24"
    foreground = "#ECF0C1"

  [colors.normal]
    black = "#000000"
    red = "#FF4D83"
    green = "#1F8C3B"
    yellow = "#1FC95B"
    blue = "#1DD3EE"
    magenta = "#8959A8"
    cyan = "#3E999F"
    white = "#FFFFFF"

  [colors.bright]
    black = "#000000"
    red = "#FF0021"
    green = "#1FC231"
    yellow = "#D5B807"
    blue = "#15A9FD"
    magenta = "#8959A8"
    cyan = "#3E999F"
    white = "#FFFFFF"
