[colors]
  [colors.primary]
    background = "#D5D6DB"
    foreground = "#565A6E"

  [colors.normal]
    black = "#0F0F14"
    red = "#8C4351"
    green = "#485E30"
    yellow = "#8F5E15"
    blue = "#34548A"
    magenta = "#5A4A78"
    cyan = "#0F4B6E"
    white = "#343B58"

  [colors.bright]
    black = "#9699A3"
    red = "#8C4351"
    green = "#485E30"
    yellow = "#8F5E15"
    blue = "#34548A"
    magenta = "#5A4A78"
    cyan = "#0F4B6E"
    white = "#343B58"
