[colors]
  [colors.primary]
    background = "#2C2C2C"
    foreground = "#CCCCCC"

  [colors.normal]
    black = "#000000"
    red = "#F27779"
    green = "#99CC99"
    yellow = "#FFCC66"
    blue = "#6699CC"
    magenta = "#CC99CC"
    cyan = "#66CCCC"
    white = "#FFFEFE"

  [colors.bright]
    black = "#000000"
    red = "#F17779"
    green = "#99CC99"
    yellow = "#FFCC66"
    blue = "#6699CC"
    magenta = "#CC99CC"
    cyan = "#66CCCC"
    white = "#FFFEFE"
