[colors]
  [colors.primary]
    background = "#002451"
    foreground = "#FFFEFE"

  [colors.normal]
    black = "#000000"
    red = "#FF9DA3"
    green = "#D1F1A9"
    yellow = "#FFEEAD"
    blue = "#BBDAFF"
    magenta = "#EBBBFF"
    cyan = "#99FFFF"
    white = "#FFFEFE"

  [colors.bright]
    black = "#000000"
    red = "#FF9CA3"
    green = "#D0F0A8"
    yellow = "#FFEDAC"
    blue = "#BADAFF"
    magenta = "#EBBAFF"
    cyan = "#99FFFF"
    white = "#FFFEFE"
