[colors]
  [colors.primary]
    background = "#424043"
    foreground = "#FCFCFA"

  [colors.normal]
    black = "#2E3436"
    red = "#FC6386"
    green = "#A9DC76"
    yellow = "#FCE94F"
    blue = "#FB976B"
    magenta = "#75507B"
    cyan = "#34E2E2"
    white = "#FFFFFF"

  [colors.bright]
    black = "#989595"
    red = "#FC6386"
    green = "#A9DC76"
    yellow = "#FCE94F"
    blue = "#FB976B"
    magenta = "#AB9DF2"
    cyan = "#34E2E2"
    white = "#D1D1C0"
