########################################################
###################     LANGUGAGES    ##################
########################################################

# ASTRO

[[language]]
name = "astro"
scope = "source.astro"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }


[[grammar]]
name = "astro"
source = { git = "https://github.com/virchau13/tree-sitter-astro", rev = "947e93089e60c66e681eba22283f4037841451e7" }

# awk

[[language]]
name = "awk"
scope = "source.awk"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "awk"
source = { git = "https://github.com/Beaglefoot/tree-sitter-awk", rev = "a799bc5da7c2a84bc9a06ba5f3540cf1191e4ee3" }

# BASH

[[language]]
name = "bash"
scope = "source.bash"
file-types = [
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = "tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin"}, 
]
auto-format = false
indent = { tab-width = 4, unit = "    " }
grammar = "bash"
language-servers = [ "bash-language-server" ]

# C

[[language]]
name = "c"
scope = "source.c"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# CMAKE

[[language]]
name = "cmake"
scope = "source.cmake"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "cmake"
source = { git = "https://github.com/uyha/tree-sitter-cmake", rev = "6e51463ef3052dd3b328322c22172eda093727ad" }

# C PLU PLUS

[[language]]
name = "cpp"
scope = "source.cpp"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# CSS

[[language]]
name = "css"
scope = "source.css"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "css"
source = { git = "https://github.com/tree-sitter/tree-sitter-css", rev = "769203d0f9abe1a9a691ac2b9fe4bb4397a73c51" }

# DEBIAN

[[language]]
name = "debian"
scope = "text.debian"
file-types = [
  "dsc",
  "changes",
  { glob = "debian/**/control" },
  { glob = "etc/apt/sources.list.d/*.sources"}
]
comment-tokens = "#"

[[grammar]]
name = "debian"
source = { git = "https://gitlab.com/MggMuggins/tree-sitter-debian", rev = "9b3f4b78c45aab8a2f25a5f9e7bbc00995bc3dde" }

# DUNSTRC

[[language]]
name = "dunstrc"
scope = "source.dunstrc"
comment-tokens = ["#", ";"]
file-types = [ { glob = "dunst/dunstrc" } ]

[[grammar]]
name = "dunstrc"
source = { git = "https://github.com/rotmh/tree-sitter-dunstrc", rev = "9cb9d5cc51cf5e2a47bb2a0e2f2e519ff11c1431" }

# ELISP

[[language]]
name = "elisp"
scope = "source.elisp"
file-types = []
auto-format = false

[language.auto-pairs]
'(' = ')'
'"' = '"'

[[grammar]]
name = "elisp"
source = { git = "https://github.com/Wilfred/tree-sitter-elisp", rev = "e5524fdccf8c22fc726474a910e4ade976dfc7bb" }

# FISH

[[language]]
name = "fish"
scope = "source.fish"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    "}

[[grammar]]
name = "fish"
source = { git = "https://github.com/ram02z/tree-sitter-fish", rev = "a78aef9abc395c600c38a037ac779afc7e3cc9e0" }

# GHOSTTY

[[language]]
name = "ghostty"
scope = "source.ghostty"
file-types = [ { glob = "ghostty/config"} ]
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "ghostty"
source = { git = "https://github.com/bezhermoso/tree-sitter-ghostty" , rev = "8438a93b44367e962b2ea3a3b6511885bebd196a" }

# GJS

[[language]]
name = "gjs"
scope = "source.gjs"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"

[language.auto-pairs]
'<' = '>'
"'" = "'"
"{" = "}"
"(" = ")"
'"' = '"'

# GO

[[language]]
name = "go"
scope = "source.go"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# HASKELL

[[language]]
name = "haskell"
scope = "source.haskell"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "haskell"
source = { git = "https://github.com/tree-sitter/tree-sitter-haskell", rev = "0975ef72fc3c47b530309ca93937d7d143523628" }

# HTML

[[language]]
name = "html"
scope = "text.html.basic"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# HYPRLANG

[[language]]
name = "hyprlang"
scope = "source.hyprlang"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# JAVASCRIPT

[[language]]
name = "javascript"
scope = "source.js"
file-types = []

auto-format = false
indent = { tab-width = 4, unit = "    " }

# JSON

[[language]]
name = "json"
scope = "source.json"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# JSONC

[[language]]
name = "jsonc"
scope = "source.json"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# JSON5

[[language]]
name = "json5"
scope = "source.json5"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }


[[grammar]]
name = "json5"
source = { git = "https://github.com/Joakker/tree-sitter-json5", rev = "c23f7a9b1ee7d45f516496b1e0e4be067264fa0d" }

# JSONNET

[[language]]
name = "jsonnet"
scope = "source.jsonnet"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }


[[grammar]]
name = "jsonnet"
source = { git = "https://github.com/sourcegraph/tree-sitter-jsonnet", rev = "0475a5017ad7dc84845d1d33187f2321abcb261d" }

# JSONX

[[language]]
name = "jsx"
auto-format = false
file-types = []
indent = { tab-width = 4, unit = "    " }
grammar = "javascript"

# LUA

[[language]]
name = "lua"
scope = "source.lua"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# MAKE

[[language]]
name = "make"
scope = "source.make"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "\t" }

[[grammar]]
name = "make"
source = { git = "https://github.com/alemuller/tree-sitter-make", rev = "a4b9187417d6be349ee5fd4b6e77b4172c6827dd" }

# MARKDOC

[[language]]
name = "markdoc"
scope = "text.markdoc"
file-types = []
auto-format = false

[[grammar]]
name = "markdoc"
source = { git = "https://github.com/markdoc-extra/tree-sitter-markdoc", rev = "5ffe71b29e8a3f94823913ea9cea51fcfa7e3bf8" }

# MARKDOWN

[[language]]
name = "markdown"
scope = "source.md"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }


[[grammar]]
name = "markdown"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown", rev = "62516e8c78380e3b51d5b55727995d2c511436d8", subpath = "tree-sitter-markdown" }

# MARKDOWN-RUSTDOC

[[language]]
name = "markdown-rustdoc"
scope = "source.markdown-rustdoc"
file-types = []
auto-format = false
grammar = "markdown"
indent = { tab-width = 2, unit = "  " }

# MARKDOWN INLINE

[[language]]
name = "markdown.inline"
scope = "source.markdown.inline"
file-types = []
auto-format = false
grammar = "markdown_inline"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "markdown_inline"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown", rev = "62516e8c78380e3b51d5b55727995d2c511436d8", subpath = "tree-sitter-markdown-inline" }

# MESON

[[language]]
name = "meson"
scope = "source.meson"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# MSBUILD

[[language]]
name = "msbuild"
scope = "source.msbuild"
file-types = []
indent = { tab-width = 2, unit = "  " }
grammar = "xml"

# NIM

[[language]]
name = "nim"
scope = "source.nim"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'[' = ']'
'"' = '"'
"'" = "'"
'{' = '}'

[[grammar]]
name = "nim"
source = { git = "https://github.com/alaviss/tree-sitter-nim", rev = "c5f0ce3b65222f5dbb1a12f9fe894524881ad590" }

# NIX

[[language]]
name = "nix"
scope = "source.nix"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "nix"
source = { git = "https://github.com/nix-community/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }

# NUNJUCKS

[[language]]
name = "nunjucks"
scope = "text.html.nunjucks"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }
grammar = "jinja2"

# JINJA

[[language]]
name = "jinja"
scope = "text.html.jinja"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }
grammar = "jinja2"

[[grammar]]
name = "jinja2"
source = { git = "https://github.com/varpeti/tree-sitter-jinja2", rev = "a533cd3c33aea6acb0f9bf9a56f35dcfe6a8eb53" }

# JQ

[[language]]
name = "jq"
scope = "source.jq"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "jq"
source = { git = "https://github.com/flurie/tree-sitter-jq", rev = "13990f530e8e6709b7978503da9bc8701d366791" }

# ORG

[[language]]
name = "org"
scope = "source.org"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "org"
source = { git = "https://github.com/milisims/tree-sitter-org", rev = "698bb1a34331e68f83fc24bdd1b6f97016bb30de" }

# PERL

[[language]]
name = "perl"
scope = "source.perl"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "perl"
source = { git = "https://github.com/tree-sitter-perl/tree-sitter-perl", rev = "72a08a496a23212f23802490ef6f4700d68cfd0e" }

# PKGBUILD

[[language]]
name = "pkgbuild"
scope = "source.bash"
file-types = []
auto-format = false
grammar = "bash"


#POWERSHELL

[[language]]
name = "powershell"
scope = "source.powershell"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "powershell"
source = { git = "https://github.com/airbus-cert/tree-sitter-powershell", rev = "c9316be0faca5d5b9fd3b57350de650755f42dc0" }

# PYTHON

[[language]]
name = "python"
scope = "source.python"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "4bfdd9033a2225cc95032ce77066b7aeca9e2efc" }

# QML

[[language]]
name = "qml"
scope = "source.qml"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }
grammar = "qmljs"

[[grammar]]
name = "qmljs"
source = { git = "https://github.com/yuja/tree-sitter-qmljs", rev = "0b2b25bcaa7d4925d5f0dda16f6a99c588a437f1" }

# RMARKDOWN

[[language]]
name = "rmarkdown"
scope = "source.rmd"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }
grammar = "markdown"


# RON

[[language]]
name = "ron"
scope = "source.ron"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "ron"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-ron", rev = "78938553b93075e638035f624973083451b29055" }

# RUBY


[[language]]
name = "ruby"
scope = "source.ruby"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "ruby"
source = { git = "https://github.com/tree-sitter/tree-sitter-ruby", rev = "206c7077164372c596ffa8eaadb9435c28941364" }

# RUST

[[language]]
name = "rust"
scope = "source.rust"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# RUST-FORMAT-ARGS

[[language]]
name = "rust-format-args"
scope = "source.rust-format-args"
file-types = []
injection-regex = "rust-format-args"

[[grammar]]
name = "rust-format-args"
source = { git = "https://github.com/nik-rev/tree-sitter-rustfmt", rev = "2ca0bdd763d0c9dbb1d0bd14aea7544cbe81309c" }

# SCSS

[[language]]
name = "scss"
scope = "source.scss"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "  " }

[[grammar]]
name = "scss"
source = { git = "https://github.com/serenadeai/tree-sitter-scss", rev = "c478c6868648eff49eb04a4df90d703dc45b312a" }

# TOML

[[language]]
name = "toml"
scope = "source.toml"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# TSX

[[language]]
name = "tsx"
scope = "source.tsx"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "tsx"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf", subpath = "tsx" }

# TYPESCRIPT

[[language]]
name = "typescript"
scope = "source.ts"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf", subpath = "typescript" }

# XML

[[language]]
name = "xml"
scope = "source.xml"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }

# YAML

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "  " }


[[grammar]]
name = "yaml"
source = { git = "https://github.com/ikatyang/tree-sitter-yaml", rev = "0e36bed171768908f331ff7dff9d956bae016efb" }

# YUCK

[[language]]
name = "yuck"
scope = "source.yuck"
file-types = []
auto-format = false
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "yuck"
source = { git = "https://github.com/Philipp-M/tree-sitter-yuck", rev = "e3d91a3c65decdea467adebe4127b8366fa47919" }

# ZIG

[[language]]
name = "zig"
scope = "source.zig"
file-types = []
auto-format = false
indent = { tab-width = 4, unit = "    " }




########################################################
################     LANGUGAGES GRAMAR      ############
########################################################

# BASH

[[grammar]]
name = "bash"
source = { git = "https://github.com/tree-sitter/tree-sitter-bash", rev = "487734f87fd87118028a65a4599352fa99c9cde8" }

# C

[[grammar]]
name = "c"
source = { git = "https://github.com/tree-sitter/tree-sitter-c", rev = "7175a6dd5fc1cee660dce6fe23f6043d75af424a" }

# C PLUS PLUS
[[grammar]]
name = "cpp"
source = { git = "https://github.com/tree-sitter/tree-sitter-cpp", rev = "56455f4245baf4ea4e0881c5169de69d7edd5ae7" }

# GO

[[grammar]]
name = "go"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }

# HTML

[[grammar]]
name = "html"
source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "29f53d8f4f2335e61bf6418ab8958dac3282077a" }


# HYPRLANG

[[grammar]]
name = "hyprlang"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang", rev = "27af9b74acf89fa6bed4fb8cb8631994fcb2e6f3"}

# JAVASCRIPT

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev = "f772967f7b7bc7c28f845be2420a38472b16a8ee" }

# JSON

[[grammar]]
name = "json"
source = { git = "https://github.com/tree-sitter/tree-sitter-json", rev = "73076754005a460947cafe8e03a8cf5fa4fa2938" }

# LUA

[[grammar]]
name = "lua"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-lua", rev = "88e446476a1e97a8724dff7a23e2d709855077f2" }

# MESON

[[grammar]]
name = "meson"
source = { git = "https://github.com/staysail/tree-sitter-meson", rev = "32a83e8f200c347232fa795636cfe60dde22957a" }

# RUST

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "1f63b33efee17e833e0ea29266dd3d713e27e321" }

# TOML

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }

# XML

[[grammar]]
name = "xml"
source = { git = "https://github.com/RenjiSann/tree-sitter-xml", rev = "48a7c2b6fb9d515577e115e6788937e837815651" }

# ZIG

[[grammar]]
name = "zig"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-zig", rev = "eb7d58c2dc4fbeea4745019dee8df013034ae66b" }


########################################################
################     LANGUGAGE SERVERS      ############
########################################################

# BASH 
[language-server]

bash-language-server = { command = "bash-language-server", args = ["start"] }

# RUST

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
